baseurl = "http://bego.io/"
languageCode = "en-us"
title = "bego.io"
theme = "creative"

googleAnalytics = "UA-52478213-10"

[params.navigation]
		brand = "<img src='/img/bego-logo.png'>"
        
[params.hero]
		slogan     = "To Be or Not to Be"
		subtitle   = """
That may be the question. What this site is all about will be clear ... soon.
"""
		buttonText = "Coming Soon"